version: '3'

services:
  client:
    build:
      context: client
      dockerfile: Dockerfile
    image: kainguyen81/fosha-client
    restart: on-failure
    ports:
      - '3000:3000'
    container_name: fosha-client
    command: >
      sh -c "npm start"
    networks:
      - node-network

  api:
    build:
      context: server
      dockerfile: Dockerfile
    image: kainguyen81/fosha-server
    restart: on-failure
    ports:
      - '3001:3001'
    container_name: fosha-server
    command: >
      sh -c "npm start"
    networks:
      - node-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./ssl:/ssl
    depends_on:
      - api
      - client
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
